### ISSUE TITLE
FPS Calculation

### ISSUE THREAD

**Issue by tobx** [IceCreamYou/MainLoop.js#12]
There might be some minor issues with the FPS calculation:
1. `FPS < 1` is currently not possible, but this might happen in test environments.
   Proposed solution: Update the EMA FPS value `n` times in each loop with the value `frameCount / n`, where `n` is the number of seconds passed since the last update.
2. FPS update intervals are currently a little longer than 1 second, because:
   `timestamp > lastFpsUpdate + 1000`.
   So currently it does not calculate:
   `frames / second`
   but:
   `frames / (second + time until next frame starts)`.
   This could be corrected this with:
   `while (lastFpsUpdate < timestamp - 1000) lastFpsUpdate += 1000;`
   instead of:
   `lastFpsUpdate = timestamp;`

**Comment by IceCreamYou** [comment]
Sorry for the delayed response - for some reason I didn't get a notification from GitHub about this issue.

Good catch on your second point, and thanks for pointing this out. I'll fix it as you suggest.

For your first point, if I understand you correctly, you're suggesting to replace this line:

``` js
fps = 0.25 * framesThisSecond + 0.75 * fps;
```

with something like this?

``` js
fps = 0.25 * (framesThisSecond / ((timestamp - lastFpsUpdate) / 1000)) + 0.75 * fps;
```

or like this?

``` js
fps = 0.25 * (framesThisSecond / Math.floor((timestamp - lastFpsUpdate) / 1000)) + 0.75 * fps;
```

In the latter case, since we'd already be computing the number of complete seconds since the last update, we could re-use the `n` value to fix the second issue you raised by doing `lastFpsUpdate += n * 1000` instead of using the `while` loop.
