### ISSUE TITLE
Deep call stack

### ISSUE THREAD

**Issue by schibo** [IceCreamYou/MainLoop.js#16]
This runs great, but the recursive call to requestAnimation causes the call stack to become pretty deep.  I'm only using the loop for update(), so maybe the issue is with how I integrated it?

I've integrated this into my N64 javascript emu at http://1964js.com.

**Comment by IceCreamYou** [comment]
I can see why it would seem like that, but that's not how this works. `requestAnimationFrame` is asynchronous; [roughly](https://www.w3.org/TR/html51/webappapis.html#animation-frames), it puts the specified function on the next frame's call stack, which is separate. This library uses the function as recommended by the [original spec](https://www.w3.org/TR/animation-timing/) and the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

**Comment by IceCreamYou** [comment]
It just occurred to me - Chrome [recently](https://developers.google.com/web/updates/2017/05/devtools-release-notes#async-stacks) changed the way errors are tracked in an async context so that you can see the call stack that initiated the async action. That may cause errors thrown in a main loop to appear to be nested very deeply. It is possible to [turn this off](https://developers.google.com/web/updates/2017/05/devtools-release-notes#async-stacks) if you want though. More details [here](https://www.html5rocks.com/en/tutorials/developertools/async-call-stack/) on how you might want to use this feature.

**Comment by schibo** [comment]
Got it, thanks for the clarification!
