### ISSUE TITLE
Why not divide out framedelta by simulationtimestep to detect a panic sooner?

### ISSUE THREAD

**Issue by Sammmmm** [IceCreamYou/MainLoop.js#17]
This may be a stupid question...

If update takes an appreciable amount of time (but still less than simulationTimeStep), wont looping through update 240 times if you're just going to bail and resync anyway just make it take longer to panic?

I assume I'm missing something.

**Comment by IceCreamYou** [comment]
It's a reasonable question.

In short, there's no assumption that the user of the library will "bail and resync." For example, some applications may wait for multiple panics before bailing, or reduce resource usage on panic (e.g. downgrade graphics from "High" to "Low" settings), or some other strategy to improve the frame rate. This is generally a good idea because a single panic could just be a fluke but many panics probably means that the application is not capable of running in a deterministic way under the current conditions.

Also, the way panics work right now, they're just a flag that gets passed to the `end` function - so there's no way to panic early if we still want to perform the updates.
