### ISSUE TITLE
update() function always called with the same parametervalue

### ISSUE THREAD

**Issue by woodyplz** [IceCreamYou/MainLoop.js#20]
Hello, 
Im new to this topic and read your mainLoop article at:
https://isaacsukin.com/news/2015/01/detailed-explanation-javascript-game-loops-and-timing#fps-control

I really found it helpful and want to try things out with this.
However I was wondering why the update(simulationTimestep) function always gets called with the same value.
Earlier in your article we passed delta as parameter, where it sent the elapsed time since the last update.
Later in the article you said it has to be called with the same delta since we would get wierd rounding errors, which leads to moving through objects.

So thinking about it is there any use for this "delta"? The calculated velocity/movement will always be the same amount anyways.

Thanks in advance.

**Comment by IceCreamYou** [comment]
It sounds like you're asking why we bother passing `simulationTimestep` to `update` instead of having, for example, a global `simulationTimestep` variable that `update` uses?

The answer is: for convenience. Using the MainLoop library, you could call `MainLoop.getSimulationTimestep()` to get the value once and then use it instead of the parameter to `update()` for the duration of your app session (assuming you didn't call `MainLoop.setSimulationTimestep()` later).

You typically wouldn't want to hardcode e.g. a velocity value that didn't take `simulationTimestep` as a factor because `simulationTimestep` is used in many places internal to the main loop so if you were to change its value it would be a pain to change derivative calculations throughout your codebase. Also, things like "velocity" are usually easier to specify and understand in units-per-second rather than, for example, units-per-17-milliseconds.
