### ISSUE TITLE
setInterval/setTimeout vs requestAnimationFrame?

### ISSUE THREAD

**Issue by dakom** [IceCreamYou/MainLoop.js#24]
Just trying to understand the approach a bit better before porting it-

Would it work to call `update(simulationTimestep)` and updating all the related variables inside setInterval/setTimeout - even if `render()` is scheduled with rAF? Talking about browsers only and assuming that the callback can call performance.now()

In other words, I'm trying to understand why physics updates are also done in rAF which, as you've mentioned is tied to the display rate and can be delayed when switching tabs etc.

Thanks!

**Comment by IceCreamYou** [comment]
There are several reasons I'm aware of to run `update` inside `rAF` instead of a timer:

- The physics updates will sync better with visual updates. Imagine for example that you're painting frames at 0ms, 17ms, 34ms, 51ms, etc. and you're updating physics at 10ms, 40ms, 70ms, etc. In that case you will get frames where there are no physics updates. Or alternatively you could run multiple physics updates for no reason in between frames. (That said, this point can be outweighed by the advantages of taking physics updates off the main thread and running them in workers, if your updates would slow down painting, especially if you're doing interpolation.)
- If the main thread gets really busy when painting, with rAF you just won't get another frame until the device is ready to process again. With timers, it's possible they could keep interrupting and contributing more to a spiral of death scenario.
- There are issues with how timers work in JavaScript. For example, `setInterval` will [attempt](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#Ensure_that_execution_duration_is_shorter_than_interval_frequency) to run updates at each interval, regardless of whether the previous one is finished. This can either result in spirals of death. Both `setTimeout` and `setInterval` [don't fire](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified) the callback at exactly the requested delay. For example `setTimeout(update, 0)` might wait 20ms to call `update` (though usually it'd be faster if the main thread is free). This isn't too bad in practice for physics updates specifically, but it exacerbates my first point above. There is also the problem of choosing a delay. If the delay is too low, you can burn battery and CPU with unnecessarily frequent updates, but if the delay is too high, you'll be waiting unnecessarily long between update calls, especially if each update takes longer than expected.

These issues are about edge cases and performance, and there are generally workarounds. I am not aware of any issues with determinism or accuracy.
