### ISSUE TITLE
`update` step implementation question

### ISSUE THREAD

**Issue by mcharytoniuk** [IceCreamYou/MainLoop.js#29]
Currently the update function is called multiple times in a row:

```javascript
numUpdateSteps = 0;
while (frameDelta >= simulationTimestep) {
    update(simulationTimestep);
    frameDelta -= simulationTimestep;

    if (++numUpdateSteps >= 240) {
        panic = true;
        break;
    }
}
```

Since it uses time delta anyway, why can't it be condensed into the single `update` call based on how much time has passed? It seems that this way would require only one `update` call for the loop to catch up instead of several at times.

```javascript
if ((simulationTimestep / frameDelta) >= 240) {
    panic = true;
}

update(frameDelta);

draw(frameDelta / simulationTimestep);
```

**Comment by IceCreamYou** [comment]
This is explained by the [comment](https://github.com/IceCreamYou/MainLoop.js/blob/gh-pages/src/mainloop.js#L626-L684) immediately prior to the code you're asking about, and the accompanying [explanatory article](http://www.isaacsukin.com/news/2015/01/detailed-explanation-javascript-game-loops-and-timing). In short, fixed-size physics timesteps enable determinism (otherwise accumulated rounding errors would cause your application to drift) and avoid large jumps (e.g. letting a character walk through walls if a frame is slow).

**Comment by mcharytoniuk** [comment]
@IceCreamYou yes, I got that, but there is only one draw call after several updates, so it won't affect large jumps either way, because the user will see the changes after those multiple calls anyway.

It goes like this (as far as I understand):

```
// frame begins
begin()
update(16ms)
update(16ms)
update(16ms)
update(16ms)
// here user actually sees some changes in the scene
draw()
end()
// frame ends
```

Instead of:

```
// frame begins
begin()
update(64ms)
// here user actually sees some changes in the scene
draw()
end()
// frame ends
```

Unless the goal was to provide `update` with the same delta always - in that case I understand the concept. Otherwise maybe there could be some option to maybe merge those calls while preserving those features? Then less resources would be consumed when it comes to the plain rendering, when physics is not that important.

**Comment by IceCreamYou** [comment]
No, that’s not right, as demoed in the article. If you have something like `if (isNotInWall(player.x + 10 * timestep)) player.x += 10 * timestep`, and timestep is 1000 instead of 16.67, the player is going to move much farther in one physics update and potentially move through a wall. Anyway, that’s not the only problem: different sized timesteps will also cause rounding error to accumulate and make your application non-deterministic within a few seconds.

**Comment by IceCreamYou** [comment]
Didn’t see your edit - yes, the point is that the timestep passed to update() must always be the same.

**Comment by mcharytoniuk** [comment]
@IceCreamYou ok, thanks for explanation.
