### ISSUE TITLE
Example that uses setBegin?

### ISSUE THREAD

**Issue by jamesplease** [IceCreamYou/MainLoop.js#30]
Hi @IceCreamYou ! I know it's been a couple of years since you've worked on this library, so no worries at all if you've moved on and don't have the time and/or interest to triage issues.

I love the example that ships with MainLoop. It really shows the value of using this library over many other solutions out there. I have a question for ya': do you happen to have another example handy that uses setBegin to process user input? It could be cool to demonstrate to folks best practices for how to use that method.

Thanks for reading!

**Comment by IceCreamYou** [comment]
Unfortunately I don't think I have any public examples of using `setBegin`, but I can provide some more detail on when it is useful (or not).

For context, when it's time to render a new frame, the sequence is:

1. `begin`
2. Zero, one, or more calls to `update`
3. `draw`
4. `end`

So what you want to put in `begin` is anything that needs to happen on every frame, but before any calls to `update`. Some good examples:

- Reading data out of DOM elements that affects updates, or changing DOM elements in a way that affects updates. One example is resizing the canvas (or other container for things you're animating) since the size of the canvas/container may affect `update` calculations
- Processing heavy input or long-running updates in batches that have to run on the main thread (as opposed to a service worker), for example if a user's click results in adding new assets to a scene, you might want to do some incremental processing on them like precalculating attributes you want to cache for use in later updates or drawing - because you wouldn't want to freeze the application to do this during an event handler, and it doesn't matter how long this takes in the background
- Responding to network events, for example a client for a networked game might have updates streaming in about other players' locations, and some global state may need to be updated from this before updates run, and maybe this takes too long to do all at once in a WebSocket message event or can't easily be delegated to a worker
- Pre-calculating state that can be shared across multiple `update` calls in the same frame, e.g. updating a timer or reading an image's dimensions

Here are some things you don't need to put in a `begin` callback:

- Simple changes from most event handlers. If the only thing you're doing in an event handler is some simple math, for example, that's likely fine because it's not typically going to result in the event handler delaying a frame by running for too long.
- Long-running processing that can be done in a worker. If you can make calculations happen off the main UI thread, that's preferable to running them before each frame.
- Anything that doesn't have to happen every frame.

Hopefully that helps.

**Comment by jamesplease** [comment]
This is incredibly helpful, @IceCreamYou ! I really appreciate you taking the time to write out such a thorough reply.
