### ISSUE TITLE
Falls back to setTimeout when bundled via Browserify

### ISSUE THREAD

**Issue by meeber** [IceCreamYou/MainLoop.js#8]
When bundled via Browserify, `this` (and thus `root`) is a reference to `module.exports` instead of `window`, so the module falls back to `setTimeout`.

Related: https://github.com/substack/node-browserify/issues/372

Thanks :D

**Comment by IceCreamYou** [comment]
Good catch. I think the simplest way to resolve this is to just reference `requestAnimationFrame` and `cancelAnimationFrame` in the global scope instead of as a property of `root` [where the polyfill is defined](https://github.com/IceCreamYou/MainLoop.js/blob/340656ca3597d593c70e713471253e7a6324fbf3/src/mainloop.js#L57-L82). That will require a `typeof` check though to avoid a `ReferenceError` error if they don't exist. An alternative would be to get the actual global object like `(0,eval)('this')`, but I think that's overkill.

**Comment by IceCreamYou** [comment]
Actually, just referencing in the global scope won't work currently because the names `requestAnimationFrame` and `cancelAnimationFrame` get initialized in local scope before we can reference them. We would need either an earlier reference or a different local name. Instead I will just check on the `window` object if it exists.

**Comment by IceCreamYou** [comment]
@meeber Can you confirm this fix works? If so, I'll tag a new release so the fix can be pulled in more easily. Thanks!

**Comment by meeber** [comment]
Confirmed: pure raf goodness with browserify. Thank you sir!

**Comment by IceCreamYou** [comment]
1.0.3 released! Thanks for testing.
